# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNSDKIssueRepro' do
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNSDKIssueRepro

  

  platform :ios, '9.0'
  target 'RNSDKIssueReproTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNSDKIssueRepro-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNSDKIssueRepro-tvOS

  target 'RNSDKIssueRepro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
